/* Created with Uzebox Patch Studio 0.0.2 */
const char patch00[] PROGMEM = {
  0, PC_WAVE, 6,
  0, PC_ENV_SPEED, -5,
  0, PATCH_END,
};
const char patch01[] PROGMEM = {
  0, PC_ENV_SPEED, -12,
  5, PC_NOTE_UP, 12,
  5, PC_NOTE_DOWN, 12,
  5, PC_NOTE_UP, 12,
  5, PC_NOTE_DOWN, 12,
  5, PC_NOTE_CUT, 0,
  0, PATCH_END,
};
const char patch02[] PROGMEM = {
  0, PC_WAVE, 10,
  0, PC_ENV_SPEED, -15,
  4, PC_ENV_SPEED, -7,
  0, PATCH_END,
};
const char patch03[] PROGMEM = {
  0, PC_WAVE, 9,
  0, PC_ENV_SPEED, -15,
  4, PC_ENV_SPEED, -7,
  0, PATCH_END,
};
const char patch04[] PROGMEM = {
  0, PC_NOISE_PARAMS, 10,
  0, PC_ENV_SPEED, -30,
  2, PC_NOISE_PARAMS, 5,
  1, PC_NOISE_PARAMS, 3,
  1, PC_NOISE_PARAMS, 1,
  2, PC_NOTE_CUT, 0,
  0, PATCH_END,
};
const char patch05[] PROGMEM = {
  0, PC_ENV_SPEED, -25,
  2, PC_NOTE_UP, 12,
  4, PC_NOTE_CUT, 0,
  0, PATCH_END,
};
const char patch06[] PROGMEM = {
  0, PC_ENV_SPEED, -15,
  0, PC_PITCH, 90,
  2, PC_NOTE_DOWN, 3,
  2, PC_NOTE_DOWN, 4,
  2, PC_NOTE_DOWN, 5,
  2, PC_NOTE_DOWN, 6,
  2, PC_NOTE_CUT, 0,
  0, PATCH_END,
};
const char patch07[] PROGMEM = {
  0, PC_NOISE_PARAMS, 1,
  0, PC_ENV_VOL, 144,
  0, PC_ENV_SPEED, -30,
  8, PC_NOTE_CUT, 0,
  0, PATCH_END,
};
const char patch08[] PROGMEM = {
  0, PC_WAVE, 8,
  1, PC_ENV_VOL, 200,
  1, PC_NOTE_HOLD, 0,
  1, PC_ENV_SPEED, -25,
  0, PATCH_END,
};
const char patch09[] PROGMEM = {
  0, PC_NOISE_PARAMS, 0,
  0, PC_ENV_VOL, 160,
  0, PC_ENV_SPEED, -20,
  1, PC_ENV_SPEED, -2,
  0, PC_NOISE_PARAMS, 1,
  0, PATCH_END,
};
const char patch10[] PROGMEM = {
  0, PC_NOISE_PARAMS, 3,
  0, PC_ENV_SPEED, -30,
  3, PC_NOISE_PARAMS, 6,
  4, PC_NOISE_PARAMS, 9,
  3, PC_NOTE_CUT, 0,
  0, PATCH_END,
};
const char patch11[] PROGMEM = {
  0, PC_WAVE, 1,
  1, PC_ENV_VOL, 200,
  1, PC_NOTE_HOLD, 0,
  1, PC_ENV_SPEED, -20,
  0, PATCH_END,
};
const char patch12[] PROGMEM = {
  0, PC_WAVE, 4,
  0, PC_ENV_SPEED, -15,
  4, PC_ENV_SPEED, -7,
  0, PATCH_END,
};
const char patch13[] PROGMEM = {
  0, PC_WAVE, 1,
  0, PC_ENV_SPEED, -15,
  0, PATCH_END,
};
const char patch14[] PROGMEM = {
  0, PC_ENV_SPEED, -19,
  0, PC_NOISE_PARAMS, 6,
  2, PC_NOISE_PARAMS, 1,
  0, PATCH_END,
};
const char patch15[] PROGMEM = {
  0, PC_ENV_SPEED, -20,
  0, PC_NOISE_PARAMS, 2,
  1, PC_ENV_VOL, 0,
  2, PC_ENV_VOL, 255,
  0, PC_NOISE_PARAMS, 3,
  0, PATCH_END,
};
const char patch16[] PROGMEM = {
  0, PC_WAVE, 8,
  0, PC_ENV_VOL, 100,
  1, PC_ENV_SPEED, 20,
  5, PC_ENV_SPEED, -9,
  0, PATCH_END,
};
const char patch17[] PROGMEM = {
  0, PC_WAVE, 9,
  0, PC_ENV_SPEED, -15,
  0, PATCH_END,
};
const char patch18[] PROGMEM = {
  0, PC_WAVE, 4,
  0, PC_ENV_SPEED, -8,
  0, PC_PITCH, 87,
  2, PC_PITCH, 85,
  2, PC_PITCH, 78,
  2, PC_PITCH, 90,
  2, PC_ENV_VOL, 128,
  8, PC_NOTE_CUT, 0,
  0, PATCH_END,
};
const char patch19[] PROGMEM = {
  0, PC_WAVE, 4,
  0, PC_ENV_SPEED, -8,
  0, PC_PITCH, 79,
  2, PC_ENV_VOL, 128,
  2, PC_PITCH, 81,
  2, PC_PITCH, 79,
  2, PC_PITCH, 77,
  2, PC_PITCH, 76,
  2, PC_PITCH, 72,
  8, PC_NOTE_CUT, 0,
  0, PATCH_END,
};
const char patch20[] PROGMEM = {
  0, PC_WAVE, 4,
  0, PC_ENV_SPEED, -8,
  0, PC_PITCH, 79,
  4, PC_ENV_VOL, 128,
  4, PC_ENV_VOL, 128,
  8, PC_NOTE_CUT, 0,
  0, PATCH_END,
};
const char patch21[] PROGMEM = {
  0, PC_WAVE, 2,
  0, PC_ENV_SPEED, -32,
  0, PC_PITCH, 93,
  4, PC_PITCH, 82,
  4, PC_PITCH, 93,
  0, PC_ENV_VOL, 222,
  4, PC_PITCH, 82,
  8, PC_NOTE_CUT, 0,
  0, PATCH_END,
};
const char patch22[] PROGMEM = {
  0, PC_WAVE, 4,
  0, PC_ENV_SPEED, -8,
  0, PC_PITCH, 93,
  2, PC_PITCH, 95,
  8, PC_NOTE_CUT, 0,
  0, PATCH_END,
};
const char patch23[] PROGMEM = {
  0, PC_WAVE, 2,
  0, PC_ENV_VOL, 222,
  0, PC_ENV_SPEED, 32,
  0, PC_TREMOLO_LEVEL, 88,
  0, PC_TREMOLO_RATE, 88,
  0, PC_PITCH, 64,
  2, PC_PITCH, 66,
  1, PC_PITCH, 64,
  2, PC_PITCH, 66,
  0, PC_ENV_SPEED, -13,
  0, PC_WAVE, 2,
  1, PC_PITCH, 64,
  2, PC_PITCH, 66,
  0, PC_WAVE, 2,
  0, PC_PITCH, 64,
  1, PC_PITCH, 66,
  2, PC_PITCH, 64,
  1, PC_PITCH, 66,
  2, PC_PITCH, 64,
  1, PC_PITCH, 66,
  2, PC_PITCH, 64,
  1, PC_ENV_SPEED, -18,
  32, PC_NOTE_CUT, 0,
  0, PATCH_END,
};
const char patch24[] PROGMEM = {
  0, PC_ENV_VOL, 0,
  4, PC_WAVE, 4,
  0, PC_ENV_VOL, 255,
  0, PC_TREMOLO_LEVEL, 144,
  0, PC_TREMOLO_RATE, 60,
  0, PC_ENV_SPEED, -5,
  1, PC_PITCH, 86,
  3, PC_NOTE_UP, 5,
  3, PC_NOTE_DOWN, 5,
  3, PC_NOTE_UP, 5,
  3, PC_NOTE_DOWN, 5,
  3, PC_NOTE_UP, 5,
  3, PC_NOTE_DOWN, 5,
  3, PC_NOTE_UP, 5,
  3, PC_NOTE_DOWN, 5,
  3, PC_NOTE_UP, 5,
  3, PC_NOTE_DOWN, 5,
  3, PC_NOTE_UP, 5,
  3, PC_NOTE_DOWN, 5,
  3, PC_NOTE_UP, 5,
  3, PC_NOTE_CUT, 0,
  0, PATCH_END,
};
const char patch25[] PROGMEM = {
  0, PC_ENV_VOL, 0,
  4, PC_WAVE, 4,
  0, PC_ENV_VOL, 255,
  0, PC_TREMOLO_LEVEL, 144,
  0, PC_TREMOLO_RATE, 60,
  0, PC_ENV_SPEED, -5,
  1, PC_PITCH, 89,
  3, PC_NOTE_UP, 5,
  3, PC_NOTE_DOWN, 5,
  3, PC_NOTE_UP, 5,
  3, PC_NOTE_DOWN, 5,
  3, PC_NOTE_UP, 5,
  3, PC_NOTE_DOWN, 5,
  3, PC_NOTE_UP, 5,
  3, PC_NOTE_DOWN, 5,
  3, PC_NOTE_UP, 5,
  3, PC_NOTE_DOWN, 5,
  3, PC_NOTE_UP, 5,
  3, PC_NOTE_DOWN, 5,
  3, PC_NOTE_UP, 5,
  3, PC_NOTE_CUT, 0,
  0, PATCH_END,
};
const char patch26[] PROGMEM = {
  0, PC_WAVE, 2,
  1, PC_NOTE_HOLD, 0,
  1, PC_ENV_SPEED, -32,
  0, PATCH_END,
};
const char patch27[] PROGMEM = {
  0, PC_WAVE, 1,
  1, PC_NOTE_HOLD, 0,
  1, PC_ENV_SPEED, -32,
  0, PATCH_END,
};
const char patch28[] PROGMEM = {
  0, PC_WAVE, 8,
  1, PC_NOTE_HOLD, 0,
  1, PC_ENV_SPEED, -32,
  0, PATCH_END,
};
const char patch29[] PROGMEM = {
  0, PC_WAVE, 5,
  1, PC_NOTE_HOLD, 0,
  1, PC_ENV_SPEED, -32,
  0, PATCH_END,
};
const char patch30[] PROGMEM = {
  0, PC_WAVE, 9,
  1, PC_NOTE_HOLD, 0,
  1, PC_ENV_SPEED, -32,
  0, PATCH_END,
};
const char patch31[] PROGMEM = {
  0, PC_WAVE, 8,
  0, PC_ENV_SPEED, -5,
  4, PC_ENV_SPEED, -20,
  0, PATCH_END,
};
const struct PatchStruct patches[] PROGMEM = {
  {0, NULL, patch00, 0, 0},
  {0, NULL, patch01, 0, 0},
  {0, NULL, patch02, 0, 0},
  {0, NULL, patch03, 0, 0},
  {1, NULL, patch04, 0, 0},
  {0, NULL, patch05, 0, 0},
  {0, NULL, patch06, 0, 0},
  {1, NULL, patch07, 0, 0},
  {0, NULL, patch08, 0, 0},
  {1, NULL, patch09, 0, 0},
  {1, NULL, patch10, 0, 0},
  {0, NULL, patch11, 0, 0},
  {0, NULL, patch12, 0, 0},
  {0, NULL, patch13, 0, 0},
  {1, NULL, patch14, 0, 0},
  {1, NULL, patch15, 0, 0},
  {0, NULL, patch16, 0, 0},
  {0, NULL, patch17, 0, 0},
  {0, NULL, patch18, 0, 0},
  {0, NULL, patch19, 0, 0},
  {0, NULL, patch20, 0, 0},
  {0, NULL, patch21, 0, 0},
  {0, NULL, patch22, 0, 0},
  {0, NULL, patch23, 0, 0},
  {0, NULL, patch24, 0, 0},
  {0, NULL, patch25, 0, 0},
  {0, NULL, patch26, 0, 0},
  {0, NULL, patch27, 0, 0},
  {0, NULL, patch28, 0, 0},
  {0, NULL, patch29, 0, 0},
  {0, NULL, patch30, 0, 0},
  {0, NULL, patch31, 0, 0},
};
#define PATCH00 0
#define PATCH01 1
#define PATCH02 2
#define PATCH03 3
#define PATCH04 4
#define PATCH05 5
#define PATCH06 6
#define PATCH07 7
#define PATCH08 8
#define PATCH09 9
#define PATCH10 10
#define PATCH11 11
#define PATCH12 12
#define PATCH13 13
#define PATCH14 14
#define PATCH15 15
#define PATCH16 16
#define PATCH17 17
#define PATCH18 18
#define PATCH19 19
#define PATCH20 20
#define PATCH21 21
#define PATCH22 22
#define PATCH23 23
#define PATCH24 24
#define PATCH25 25
#define PATCH26 26
#define PATCH27 27
#define PATCH28 28
#define PATCH29 29
#define PATCH30 30
#define PATCH31 31
